name: ui
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.5"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  i18n:
    path: ../i18n
  assets:
    path: ../../packages/assets
  core:
    path: ../../packages/core
  get_it: ^8.3.0
  injectable: ^2.5.2
  firebase_auth: ^6.1.1
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.1
  reactive_forms: ^18.1.1
  qr_flutter: ^4.1.0
  shorebird_code_push: ^2.0.5
  package_info_plus: ^9.0.0
  confetti: ^0.8.0
  font_awesome_flutter: ^10.12.0
  cached_network_image: ^3.4.1
  mobile_scanner: ^7.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1
  injectable_generator: ^2.9.0

flutter:
  uses-material-design: true
  assets:
    - packages/assets/logo/logo.svg
    - packages/assets/images/background.svg