name: sorting_ceremony
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.5"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  i18n:
    path: ../i18n
  auth:
    path: ../auth
  ui:
    path: ../ui
    
  get_it: ^8.3.0
  flutter_bloc: ^9.1.1
  firebase_auth: ^6.1.1
  cloud_functions: ^6.0.3
  cloud_firestore: ^6.0.3
  injectable: ^2.5.2
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1
  injectable_generator: ^2.9.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
